version: '3.7'

services:
  gunicorn:
    image: hairsalon:latest
    container_name: hairsalon
    volumes:
      - .:/usr/src/hairsalon/
      - hairsalon:/var/run/hairsalon
  nginx:
    image: nginx:1.17.7
    container_name: nginx
    depends_on:
      - gunicorn
    ports:
      - 8000:8000
    volumes:
      - ./hairsalon.conf:/etc/nginx/conf.d/default.conf
      - hairsalon:/var/run/hairsalon
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - nginx
    environment:
      DOMAINS: '${DOMAIN} -> http://nginx:8000'
      # STAGE: 'production' # Don't use production until staging works
    volumes:
      - https-portal-data:/var/lib/https-portal
volumes:
  hairsalon:
    driver: local
  https-portal-data: