# Generated by Django 3.2 on 2021-07-06 03:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hairsalon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vertical_cells_count', models.IntegerField()),
                ('horizontal_cells_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hairsalon.salon')),
            ],
            options={
                'verbose_name': 'ポイントカード',
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stamped_at', models.DateTimeField()),
                ('is_already_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customeruser')),
                ('pointcard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pointcard.pointcard')),
            ],
            options={
                'verbose_name': 'スタンプ',
            },
        ),
    ]
