# Generated by Django 3.2 on 2021-06-23 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hairsalon', '0001_initial'),
        ('pointcard', '0002_auto_20210623_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stamped_at', models.DateTimeField()),
                ('is_already_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointcard.customeruser')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hairsalon.salon')),
            ],
            options={
                'verbose_name': '予約',
            },
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
