# Generated by Django 3.2 on 2021-06-23 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pointcard', '0003_auto_20210623_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stamp',
            options={'verbose_name': 'スタンプ'},
        ),
        migrations.AlterField(
            model_name='stamp',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
