# Generated by Django 3.2 on 2021-07-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_salonstaff_salon'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonstaff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='salonstaff',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
