# Generated by Django 3.2 on 2021-07-17 07:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hairsalon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('ct', 'カット'), ('cl', 'カラー'), ('tr', 'トリートメント')], max_length=2)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuSet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuSetRelation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairsalon.menu')),
                ('set_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hairsalon.menuset')),
            ],
        ),
    ]
